<h3>Novo Fornecedor</h3>
<br />
<?php

$form = $this->form;
$form->setAttribute('action',$this->url('Provider/default',array('controller'=>'Provider','action'=>'new')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '<b>Nome:</b> ' .$this->formInput($form->get('nome')) . '<br>'. '<br>';
echo '<b>Telefone:</b> ' .$this->formInput($form->get('phone')) . '<br>'. '<br>';
echo '<b>Endereço:</b> ' .$this->formInput($form->get('address')) . '<br>'. '<br>';
echo '<b>Cidade:</b> ' .$this->formInput($form->get('city')) . '<br>'. '<br>';
echo '<b>UF:</b> ' .$this->formInput($form->get('uf')) . '<br>'. '<br>';
echo '<b>Fornecedor Ativo?:</b> ' .$this->formRadio($form->get('status')) . '<br>'. '<br>';
echo $this->formSubmit($form->get('submit')) . '<br>'. '<br>';
echo $this->form()->closeTag();
?>