<h3>SCIE - Sistema de Controle e Interação de Estoque</h3>

<br />

<?php if($this->error): ?>
<p>Usuário ou senha inválidos</p>
<?php endif; ?>

<?php

$form = $this->form;
$form->setAttribute('action',$this->url('login'));
$form->prepare();

echo $this->form()->openTag($form);

echo '<b>Email: </b>' . $this->formInput($form->get('email')) . '<br><br>';
echo '<b>Senha: </b>' . $this->formInput($form->get('password')). '<br><br>';
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();

?>
