<h1>Relatorios</h1>

<br />
<p>
    <a href="<?php echo $this->url('Report/default',array('action'=>'estoque')); ?>">Relatório de Estoque por Mês</a>
</p>
<p>
    <a href="<?php echo $this->url('Report/default',array('action'=>'financeiro')); ?>">Relatório Financeiro</a>
</p>
<p>
    <a href="<?php echo $this->url('Report/default',array('action'=>'new')); ?>">Relatório de Itens Defeituosos ou com Falhas</a>
</p>
</p>
<br />
